# Turns an arbitrary text file into a C++ header exposing it as a
# std::string_view. Used to bake dashboard/index.html into the server binary so
# that `bourse-server` is a single self-contained artefact with no asset paths
# to get wrong at deploy time.
#
# Invoked at build time via `cmake -P` (see the root CMakeLists.txt).

if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED VARIABLE_NAME)
  message(FATAL_ERROR "EmbedAsset.cmake requires INPUT_FILE, OUTPUT_FILE and VARIABLE_NAME")
endif()

file(READ "${INPUT_FILE}" content HEX)

string(LENGTH "${content}" hex_len)
math(EXPR byte_count "${hex_len} / 2")

set(body "")
set(i 0)
set(col 0)
while(i LESS hex_len)
  string(SUBSTRING "${content}" ${i} 2 byte)
  string(APPEND body "'\\x${byte}',")
  math(EXPR col "${col} + 1")
  if(col EQUAL 20)
    string(APPEND body "\n    ")
    set(col 0)
  endif()
  math(EXPR i "${i} + 2")
endwhile()

get_filename_component(out_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${out_dir}")

file(WRITE "${OUTPUT_FILE}"
"// Generated by cmake/EmbedAsset.cmake from ${INPUT_FILE}. Do not edit.
#pragma once

#include <string_view>

namespace bourse::assets {

inline constexpr char ${VARIABLE_NAME}Data[] = {
    ${body}
};

inline constexpr std::string_view ${VARIABLE_NAME}{${VARIABLE_NAME}Data, ${byte_count}};

}  // namespace bourse::assets
")
